CREATE TABLE IF NOT EXISTS files (
    id SERIAL PRIMARY KEY,
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
    filename VARCHAR(255) NOT NULL,
    latency FLOAT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
